### ISSUE TITLE
Support for string arguments with spaces

### ISSUE THREAD

**Issue by ac-arcana** [jitspoe/godot-console#11]
Currently with arguments separated by spaces there is no way to include a string as an argument with a space in it. I propose optionally using quotes in the arguments to denote a string that can include spaces.

**Comment by MolikoDeveloper** [comment]
you can make it with a ReGex, where you can separate "string separated by comma" with arguments separated by comma.

**Comment by jitspoe** [comment]
I think I want to avoid RegEx.  I don't know if this is still the case, but at one point in time, somebody was trying to port something I made to the Nintendo Switch, and it wasn't possible because of regex.  Apparently the Switch does not allow JIT compiled stuff, which the regex library used.  Don't want to cause any headaches for devs who are using this if that's still the case!

**Comment by MolikoDeveloper** [comment]
ohhh the switch does not support regex? thanks for the info, in that case, have to be a parser or a reget to solve that problem?

**Comment by jitspoe** [comment]
Not 100% sure if that's still the case, but I'll just avoid them now to be safe.  I think it shouldn't be too bad to just check if the first character after a space is a ", then scan along until the next ".  Also need to check for \'s, so you can use \" if you WANT a quote in your string.  Might be worth supporting more escape characters as well, like \n for newlines.

**Comment by jitspoe** [comment]
Added support for quotes for strings with spaces as well as escape codes (so you can have quotes in things, as well as \n, etc.) here: https://github.com/jitspoe/godot-console/commit/c1b444efc468f56e6b956c320ce72eb3c523091c
